sudo: required

language: generic

env:
  - DOCKER_COMPOSE_VERSION=1.14.0

services:
  - docker

install:
  # Installing docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  # Check docker & docker-compose versions
  - docker --version
  - docker-compose --version

script:
  - docker-compose build
  - docker-compose up -d
  # Verifications
  - sleep 30
  - docker-compose logs
  - docker ps -a
  - curl --retry 20 --retry-delay 5 -D- http://localhost:9200/
  - curl --retry 20 --retry-delay 5 -D- http://localhost:5601/api/status
  - ./test.sh
