sudo: required

language: generic

env:
  - DOCKER_COMPOSE_VERSION=1.8.0

before_script:
  # Check docker & docker-compose versions
  - docker --version
  - docker-compose --version

script:
  - docker-compose build
  - docker-compose up -d

  # Verifications
  - sleep 30
  - docker-compose logs
  - curl --retry 10 --retry-delay 5 -D- http://localhost:9200/
  - curl --retry 10 --retry-delay 5 -D- http://localhost:5601/api/status
  - ./test.sh
