sudo: required

language: generic

env:
  - DOCKER_COMPOSE_VERSION=1.14.0

services:
  - docker

install:
  # Installing docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  # Check docker & docker-compose versions
  - docker --version
  - docker-compose --version

script:
  - docker-compose build
  - docker-compose up -d
  # Verifications
  - sleep 120
  - docker-compose logs
  - docker ps -a
  - curl --retry 20 --retry-delay 5 -D- http://127.0.0.1:9200/
  - curl --retry 20 --retry-delay 5 -D- http://127.0.0.1:5601/api/status
  - curl -X POST \
      http://127.0.0.1:8080/org/test_org \
      -H 'Accept: application/json' \
      -H 'Content-Type: application/json' \
      -d '[{
          "eventSubmissionTime":1526520197540,
          "version":2,
          "eventName":"Estimated loading on vessel",
          "originatorId":"OrgId",
          "eventOccurrenceTime":1527188400000,
          "eventOccurrenceTime8601":"2018-05-24T19:00:00Z",
          "originatorName":"OriginatorName",
          "containerTransportId":"Test",
          "transportationPhase":"Export",
          "eventTransactionId":"f19e26b6-example-4051-9042-5a2ee6b05797",
          "eventType":"E457",
          "associatedShipmentRefs":[
             "exampleRef"
          ],
          "associatedShipmentIds":[
             "8efdf954-example-476a-b13e-c5f217bb21230"
          ],
          "location":{
             "type":"UN/Locode",
             "value":"SGSIN"
          }
       }
    ]'
